# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [5]:
def fun(x):
  if x[0]==x[len(x)-1]:
    return True
  else:
    return False


# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

print(fun(numbers_x))
print(fun(numbers_y))

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [12]:
#code here
import numpy as np

arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(4,8).reshape(2,2)

sum = arr1 + arr2
print('Sum:')
print( sum)

product = arr1 * arr2
print('Product:')
print(product)

Sum:
[[ 4  6]
 [ 8 10]]
Product:
[[ 0  5]
 [12 21]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [27]:
#code here

arr = np.arange(12)
arr = arr.reshape(3,4)
print(arr)

a = np.arange(0,4)
b= np.arange(4,8)

hstack = np.hstack((a,b))
vstack = np.vstack((a,b))

print(hstack)
print(vstack))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [40]:
#Code here
shopping_cart = []

print("------>>> WELCOME TO ONLINE STORE <<<------")
products = ['iPad', 'Laptop', 'Smart Phone']

while(True):
  print("Shopping Products: \n1.iPad \n2.Laptop \n3.Smart Phone\n")
  choice = input("Enter your choice(1-3): ")
  if choice=='q':
    print("\nYOUR CART:\n")
    print(shopping_cart)
    print("\nThank You! GOOD BYE!!!")
    break

  elif int(choice)==1:
    shopping_cart.append(products[0])
    print(products[0], "added to cart.\n")
  elif int(choice)==2:
    shopping_cart.append(products[1])
    print(products[1], "added to cart.\n")
  elif int(choice)==3:
    shopping_cart.append(products[2])
    print(products[2], "added to cart.\n")
  else:
    print("INVALID INPUT! Try Again.")
    continue




------>>> WELCOME TO ONLINE STORE <<<------
Shopping Products: 
1.iPad 
2.Laptop 
3.Smart Phone

Enter your choice(1-3): 1
iPad added to cart.

Shopping Products: 
1.iPad 
2.Laptop 
3.Smart Phone

Enter your choice(1-3): 2
Laptop added to cart.

Shopping Products: 
1.iPad 
2.Laptop 
3.Smart Phone

Enter your choice(1-3): 4
INVALID INPUT! Try Again.
Shopping Products: 
1.iPad 
2.Laptop 
3.Smart Phone

Enter your choice(1-3): q

YOUR CART:

['iPad', 'Laptop']

Thank You! GOOD BYE!!!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [42]:
#code here

def classify_emails(a):
  category = []
  for i in a:
    for k, v in dict.items():
      for j in v:
        if j in i.lower():
          category.append(k)
          break
  return category

dict = {
        "Important" : ["account", "balance", "delivery"],
        "Promotions" : ["offer", "buy", "order"],
        "Spam" : ["free", "click"]
      }



a = ["Your acccount balance is low.", "We offer high quality fragrances.", "Click here, Now free!"]

result = classify_emails(a)
print(result)

['Important', 'Promotions', 'Spam']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [45]:
#code here

dict = {
        "hello" : "hola",
        "goodbye" : "adios",
        "cat" : "gato" ,
        "book" : "libro"
      }

while(True):
  inp = input("Enter Eng Word: ")
  if inp =="q":
    print("\nQUITTING...\n")
    break

  check = False
  for k, v in dict.items():
    if k == inp.lower():
      check =True
      print("Spanish:", v)

  if check==False:
    print("Sorry! Word Not Found in Dictionary.")


Enter Eng Word: hello
Spanish: hola
Enter Eng Word: book
Spanish: libro
Enter Eng Word: class
Sorry! Word Not Found in Dictionary.
Enter Eng Word: q

QUITTING...



# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [46]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")

In [47]:
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [49]:
global_sum = df["Global_Sales"].sum()
print("Total Global Sales:", global_sum )

Total Global Sales: 8920.44


In [56]:
temp_df = df.sort_values(by="Global_Sales", ascending=False)
temp_df["Name"][0]

'Wii Sports'

In [59]:
print(df["NA_Sales"].mean())
print(df["EU_Sales"].mean())
print(df["JP_Sales"].mean())
print(df["Other_Sales"].mean())

0.26466742981082064
0.14665200626581515
0.077781660441017
0.0480630196409206


In [89]:
temp = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
temp

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

In [94]:
temp = df.groupby('Genre')['Global_Sales'].sum()
temp

Genre
Action          1751.18
Adventure        239.04
Fighting         448.91
Misc             809.96
Platform         831.37
Puzzle           244.95
Racing           732.04
Role-Playing     927.37
Shooter         1037.37
Simulation       392.20
Sports          1330.93
Strategy         175.12
Name: Global_Sales, dtype: float64

In [71]:
# temp_df = df.groupby(['Genre', 'NA_Sales']).sum()
temp_df = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print(temp_df)

              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [112]:
temp_df = df.groupby('Genre')['NA_Sales'].sum()
temp = pd.DataFrame(temp_df)
temp = temp.sort_values(by="NA_Sales", ascending=False)
temp.head(1)

NA_Sales
Genre           
Action    877.83

In [107]:
temp_df = df.groupby('Genre')['Global_Sales'].sum()


Global_Sales
Genre                     
Action             1751.18
Sports             1330.93
Shooter            1037.37
Role-Playing        927.37
Platform            831.37

In [65]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [93]:
temp_df = df.sort_values(by="Global_Sales", ascending=False)
temp_df.head(3)['Platform']

0    Wii
1    NES
2    Wii
Name: Platform, dtype: object

In [97]:
temp = df.groupby('Genre')["Global_Sales"].sum()
temp/global_sum *100

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [99]:
c = df["NA_Sales"].corr(df["EU_Sales"])
c

0.7677267483702631